# Generated by Django 3.0.9 on 2020-08-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='displayname',
            field=models.CharField(max_length=60),
        ),
    ]
